# Generated by Django 4.2.26 on 2025-11-24 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("downloads", "0002_document_is_reserved"),
        ("diaspora", "0002_lifeinitaly_successstoryimage_testimonial_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("universities", "Lazio Universities Group"),
                            ("students", "Rome Cameroonian Students"),
                            ("professionals", "Professionals in Lazio"),
                            ("new_students", "New Students Support Group"),
                            ("women", "Women in the Diaspora Group"),
                        ],
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Public groups are visible to all authenticated users.",
                        verbose_name="Is Public",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="community_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Members",
                    ),
                ),
            ],
            options={
                "verbose_name": "Community Group",
                "verbose_name_plural": "Community Groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StoryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="story_images/%Y/%m/", verbose_name="Image"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Caption"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
            ],
            options={
                "verbose_name": "Story Image",
                "verbose_name_plural": "Story Images",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "admin_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="Admin Response"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved At"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Support Ticket",
                "verbose_name_plural": "Support Tickets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserStorySubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("story", models.TextField(verbose_name="Story")),
                (
                    "documents",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="story_documents/%Y/%m/",
                        verbose_name="Supporting Documents",
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, the story will be published without your name.",
                        verbose_name="Anonymous",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("published", "Published"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, null=True, verbose_name="Admin Notes"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Submitted At"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="story_submissions",
                        to="dashboard.storyimage",
                        verbose_name="Images",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Submission",
                "verbose_name_plural": "Story Submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "is_admin_reply",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this reply is from an admin.",
                        verbose_name="Admin Reply",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_replies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="dashboard.supportticket",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Reply",
                "verbose_name_plural": "Ticket Replies",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Subject")),
                ("question", models.TextField(verbose_name="Question")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Residence Permit, University Enrollment, etc.",
                        max_length=50,
                        null=True,
                        verbose_name="Category",
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Resolved"),
                ),
                (
                    "admin_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="Admin Response"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved At"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Question",
                "verbose_name_plural": "Student Questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrientationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferred_date", models.DateField(verbose_name="Preferred Date")),
                ("preferred_time", models.TimeField(verbose_name="Preferred Time")),
                (
                    "topics",
                    models.TextField(
                        help_text="What topics would you like to discuss?",
                        verbose_name="Topics of Interest",
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(default=False, verbose_name="Confirmed"),
                ),
                (
                    "confirmed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmed Date & Time"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orientation_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orientation Session",
                "verbose_name_plural": "Orientation Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="group_files/%Y/%m/", verbose_name="File"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="dashboard.communitygroup",
                        verbose_name="Group",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_group_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group File",
                "verbose_name_plural": "Group Files",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupDiscussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_discussions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussions",
                        to="dashboard.communitygroup",
                        verbose_name="Group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Discussion",
                "verbose_name_plural": "Group Discussions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="Pinned"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="dashboard.communitygroup",
                        verbose_name="Group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Announcement",
                "verbose_name_plural": "Group Announcements",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saved_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Saved At"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by_users",
                        to="downloads.document",
                        verbose_name="Document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Document",
                "verbose_name_plural": "Saved Documents",
                "ordering": ["-saved_at"],
                "unique_together": {("user", "document")},
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_code",
                    models.CharField(
                        help_text="Unique code for QR code generation.",
                        max_length=50,
                        unique=True,
                        verbose_name="Registration Code",
                    ),
                ),
                (
                    "attended",
                    models.BooleanField(default=False, verbose_name="Attended"),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registered At"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="diaspora.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Registration",
                "verbose_name_plural": "Event Registrations",
                "ordering": ["-registered_at"],
                "unique_together": {("event", "user")},
            },
        ),
    ]
