# Generated by Django 5.2.8 on 2026-01-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitygroup",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Cover image for the group (recommended size: 1200x400px)",
                null=True,
                upload_to="groups/covers/",
                verbose_name="Cover Image",
            ),
        ),
        migrations.AddField(
            model_name="communitygroup",
            name="featured",
            field=models.BooleanField(
                default=False,
                help_text="Featured groups appear prominently on the groups directory.",
                verbose_name="Featured",
            ),
        ),
        migrations.AddField(
            model_name="communitygroup",
            name="rules",
            field=models.TextField(
                blank=True,
                help_text="Rules and guidelines for group members.",
                verbose_name="Group Rules",
            ),
        ),
        migrations.AddField(
            model_name="communitygroup",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text='Comma-separated tags for the group (e.g., "students, rome, support")',
                max_length=500,
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="communitygroup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AddField(
            model_name="userstorysubmission",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Main cover image for the story",
                null=True,
                upload_to="story_covers/%Y/%m/",
                verbose_name="Cover Image",
            ),
        ),
        migrations.AddField(
            model_name="userstorysubmission",
            name="featured",
            field=models.BooleanField(
                default=False,
                help_text="Featured stories appear prominently on the diaspora page.",
                verbose_name="Featured",
            ),
        ),
        migrations.AddField(
            model_name="userstorysubmission",
            name="location",
            field=models.CharField(
                blank=True,
                help_text='Location related to the story (e.g., "Rome, Italy")',
                max_length=200,
                verbose_name="Location",
            ),
        ),
        migrations.AddField(
            model_name="userstorysubmission",
            name="published_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when story was published (set automatically when status changes to published)",
                null=True,
                verbose_name="Published Date",
            ),
        ),
        migrations.AddField(
            model_name="userstorysubmission",
            name="submission_type",
            field=models.CharField(
                choices=[
                    ("success", "Success Story"),
                    ("journey", "Journey Story"),
                    ("advice", "Advice & Tips"),
                    ("experience", "Personal Experience"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
                verbose_name="Submission Type",
            ),
        ),
        migrations.AddField(
            model_name="userstorysubmission",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text='Comma-separated tags (e.g., "student, rome, success")',
                max_length=500,
                verbose_name="Tags",
            ),
        ),
    ]
