# Generated by Django 5.2.14 on 2026-05-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_bureaumessage_bureaumessagereply"),
    ]

    operations = [
        migrations.AddField(
            model_name="bureaumessage",
            name="email_delivery_error",
            field=models.TextField(blank=True, verbose_name="Email Delivery Error"),
        ),
        migrations.AddField(
            model_name="bureaumessage",
            name="email_delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Email Delivery Status",
            ),
        ),
    ]
