# Generated by Django 5.2.8 on 2025-11-30 22:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("diaspora", "0002_lifeinitaly_successstoryimage_testimonial_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssociationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("statute", "Statute"),
                            ("rules_of_procedure", "Rules of Procedure"),
                            ("minutes", "Minutes"),
                            ("report", "Report"),
                            ("financial_report", "Financial Report"),
                            ("audit_report", "Audit Report"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Document Type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Version"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "Français"),
                            ("it", "Italiano"),
                        ],
                        default="en",
                        max_length=2,
                        verbose_name="Language",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="governance/documents/%Y/%m/", verbose_name="File"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "publication_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Publication Date",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the current active version",
                        verbose_name="Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Association Document",
                "verbose_name_plural": "Association Documents",
                "ordering": ["-publication_date", "document_type"],
            },
        ),
        migrations.CreateModel(
            name="BoardOfAuditors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g., "2024-2026 Board of Auditors"',
                        max_length=200,
                        verbose_name="Board Name",
                    ),
                ),
                ("term_start", models.DateField(verbose_name="Term Start")),
                (
                    "term_end",
                    models.DateField(
                        help_text="2 years from start, renewable",
                        verbose_name="Term End",
                    ),
                ),
                (
                    "is_renewed",
                    models.BooleanField(default=False, verbose_name="Renewed Term"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed")],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Board of Auditors",
                "verbose_name_plural": "Boards of Auditors",
                "ordering": ["-term_start"],
            },
        ),
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "election_type",
                    models.CharField(
                        default="executive_board",
                        help_text="Currently only Executive Board elections",
                        max_length=50,
                        verbose_name="Election Type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateField(
                        help_text="Must be within 90 days of commission formation",
                        verbose_name="End Date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Election",
                "verbose_name_plural": "Elections",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ElectoralCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g., "2024 Electoral Commission"',
                        max_length=200,
                        verbose_name="Commission Name",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed")],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Electoral Commission",
                "verbose_name_plural": "Electoral Commissions",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ExecutiveBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term_start_date", models.DateField(verbose_name="Term Start Date")),
                (
                    "term_end_date",
                    models.DateField(
                        help_text="2 years from start date, renewable once",
                        verbose_name="Term End Date",
                    ),
                ),
                (
                    "is_renewed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a renewed term (max 1 renewal allowed)",
                        verbose_name="Renewed Term",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Executive Board",
                "verbose_name_plural": "Executive Boards",
                "ordering": ["-term_start_date"],
            },
        ),
        migrations.CreateModel(
            name="GeneralAssembly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assembly_type",
                    models.CharField(
                        choices=[
                            ("agm", "Ordinary General Assembly (AGM)"),
                            ("agex", "Extraordinary General Assembly (AGEX)"),
                            ("egm", "Elective General Assembly (EGM)"),
                        ],
                        max_length=10,
                        verbose_name="Assembly Type",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Assembly Date")),
                ("location", models.CharField(max_length=200, verbose_name="Location")),
                (
                    "convocation_date",
                    models.DateField(
                        help_text="Date when notice was published (must be at least 10 days before assembly)",
                        verbose_name="Convocation Date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "minutes_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Minutes (English)"
                    ),
                ),
                (
                    "minutes_fr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Minutes (Français)"
                    ),
                ),
                (
                    "minutes_it",
                    models.TextField(
                        blank=True, null=True, verbose_name="Minutes (Italiano)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "General Assembly",
                "verbose_name_plural": "General Assemblies",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AgendaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("finance", "Finance"),
                            ("activities", "Activities"),
                            ("miscellaneous", "Miscellaneous"),
                            ("statute_amendment", "Statute Amendment"),
                            ("election", "Election"),
                            ("other", "Other"),
                        ],
                        default="miscellaneous",
                        max_length=30,
                        verbose_name="Item Type",
                    ),
                ),
                (
                    "proposal_date",
                    models.DateField(
                        help_text="Must be at least 14 days before assembly",
                        verbose_name="Proposal Date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("approved", "Approved"),
                            ("discussed", "Discussed"),
                            ("resolved", "Resolved"),
                        ],
                        default="proposed",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order in agenda",
                        verbose_name="Order",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposed_agenda_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Proposed By",
                    ),
                ),
                (
                    "assembly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_items",
                        to="governance.generalassembly",
                        verbose_name="General Assembly",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agenda Item",
                "verbose_name_plural": "Agenda Items",
                "ordering": ["assembly", "order", "title"],
            },
        ),
        migrations.CreateModel(
            name="AssociationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("cultural", "Cultural"),
                            ("educational", "Educational"),
                            ("social", "Social"),
                            ("national_day_feb11", "National Day - February 11"),
                            ("national_day_may20", "National Day - May 20"),
                            ("march8", "March 8 - Women's Day"),
                            ("december31", "December 31"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Event Type",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("start_date", models.DateTimeField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End Date"
                    ),
                ),
                ("location", models.CharField(max_length=200, verbose_name="Location")),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Budget",
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Revenue",
                    ),
                ),
                (
                    "expenses",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Expenses",
                    ),
                ),
                (
                    "report",
                    models.TextField(
                        blank=True,
                        help_text="Required after each event",
                        null=True,
                        verbose_name="Post-Event Report",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "diaspora_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="association_events",
                        to="diaspora.event",
                        verbose_name="Diaspora Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Association Event",
                "verbose_name_plural": "Association Events",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="AuditReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Period Start")),
                ("period_end", models.DateField(verbose_name="Period End")),
                (
                    "report_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Report Date"
                    ),
                ),
                ("findings", models.TextField(verbose_name="Findings")),
                (
                    "recommendations",
                    models.TextField(
                        blank=True, null=True, verbose_name="Recommendations"
                    ),
                ),
                (
                    "financial_verification_status",
                    models.CharField(
                        default="pending",
                        help_text='e.g., "Verified", "Issues Found", "Pending Review"',
                        max_length=50,
                        verbose_name="Financial Verification Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_reports",
                        to="governance.boardofauditors",
                        verbose_name="Board of Auditors",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Report",
                "verbose_name_plural": "Audit Reports",
                "ordering": ["-report_date", "-period_end"],
            },
        ),
        migrations.CreateModel(
            name="Communication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "communication_type",
                    models.CharField(
                        choices=[
                            ("announcement", "Announcement"),
                            ("notice", "Notice"),
                            ("report", "Report"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Communication Type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all_members", "All Members"),
                            ("active_members", "Active Members"),
                            ("executive_board", "Executive Board"),
                            ("general_assembly", "General Assembly"),
                            ("public", "Public"),
                        ],
                        default="all_members",
                        max_length=30,
                        verbose_name="Target Audience",
                    ),
                ),
                (
                    "publication_channels",
                    models.CharField(
                        choices=[
                            ("whatsapp_forum", "WhatsApp Forum"),
                            ("social_networks", "Social Networks"),
                            ("both", "Both"),
                            ("internal", "Internal Only"),
                        ],
                        default="both",
                        max_length=20,
                        verbose_name="Publication Channels",
                    ),
                ),
                (
                    "publication_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Publication Date",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this has been published",
                        verbose_name="Published",
                    ),
                ),
                (
                    "requires_president_approval",
                    models.BooleanField(
                        default=True,
                        help_text="As per Article 19",
                        verbose_name="Requires President Approval",
                    ),
                ),
                (
                    "president_approved",
                    models.BooleanField(
                        default=False, verbose_name="President Approved"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "president_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_communications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        help_text="Communication and Culture Manager",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_communications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Published By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Communication",
                "verbose_name_plural": "Communications",
                "ordering": ["-publication_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisciplinaryCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            (
                                "forum_confusion",
                                "Confusion in Forums/Social Networks/Debates",
                            ),
                            ("public_insult", "Public Insult"),
                            ("assault_battery", "Intentional Assault and Battery"),
                            (
                                "non_compliance",
                                "Non-compliance with Statutes and Rules",
                            ),
                            ("indiscipline", "General Indiscipline"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Violation Type",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "evidence",
                    models.TextField(
                        blank=True,
                        help_text="Links, screenshots, or other evidence",
                        null=True,
                        verbose_name="Evidence",
                    ),
                ),
                (
                    "reported_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Reported Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reported By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplinary Case",
                "verbose_name_plural": "Disciplinary Cases",
                "ordering": ["-reported_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisciplinarySanction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sanction_type",
                    models.CharField(
                        choices=[
                            ("request_explanation", "Request for Explanation"),
                            ("warning", "Warning"),
                            ("blame", "Blame"),
                            ("exclusion", "Exclusion"),
                        ],
                        max_length=30,
                        verbose_name="Sanction Type",
                    ),
                ),
                (
                    "applied_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Applied Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("appealed", "Appealed"),
                            ("resolved", "Resolved"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True,
                        help_text="For temporary sanctions",
                        null=True,
                        verbose_name="Expiration Date",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        help_text="Executive Board",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_sanctions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Applied By",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sanctions",
                        to="governance.disciplinarycase",
                        verbose_name="Disciplinary Case",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplinary Sanction",
                "verbose_name_plural": "Disciplinary Sanctions",
                "ordering": ["-applied_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Candidacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("president", "President"),
                            ("vice_president", "Vice-President"),
                            ("secretary_general", "Secretary General"),
                            ("deputy_secretary_general", "Deputy Secretary General"),
                            ("treasurer", "Treasurer"),
                            ("statutory_auditor", "Statutory Auditor"),
                            (
                                "communication_culture_manager",
                                "Communication and Culture Manager",
                            ),
                        ],
                        max_length=50,
                        verbose_name="Position",
                    ),
                ),
                (
                    "application_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Application Date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "seniority_verified",
                    models.BooleanField(
                        default=False,
                        help_text="1+ year seniority in association",
                        verbose_name="Seniority Verified",
                    ),
                ),
                (
                    "lazio_residence_verified",
                    models.BooleanField(
                        default=False, verbose_name="Lazio Residence Verified"
                    ),
                ),
                (
                    "cameroonian_origin_verified",
                    models.BooleanField(
                        default=False, verbose_name="Cameroonian Origin Verified"
                    ),
                ),
                (
                    "eligibility_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Eligibility Notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidacies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Candidate",
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidacies",
                        to="governance.election",
                        verbose_name="Election",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidacy",
                "verbose_name_plural": "Candidacies",
                "ordering": ["election", "position", "application_date"],
                "unique_together": {("election", "candidate", "position")},
            },
        ),
        migrations.AddField(
            model_name="election",
            name="commission",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="elections",
                to="governance.electoralcommission",
                verbose_name="Electoral Commission",
            ),
        ),
        migrations.CreateModel(
            name="EventOrganizingCommittee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Role/Responsibility",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizing_committees",
                        to="governance.associationevent",
                        verbose_name="Event",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="event_committees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Committee Members",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Organizing Committee",
                "verbose_name_plural": "Event Organizing Committees",
            },
        ),
        migrations.CreateModel(
            name="BoardMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meeting_date", models.DateTimeField(verbose_name="Meeting Date")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Location"
                    ),
                ),
                ("agenda", models.TextField(verbose_name="Agenda")),
                (
                    "minutes",
                    models.TextField(blank=True, null=True, verbose_name="Minutes"),
                ),
                (
                    "decisions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Decisions Made"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="board_meetings_attended",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Attendees",
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="governance.executiveboard",
                        verbose_name="Executive Board",
                    ),
                ),
            ],
            options={
                "verbose_name": "Board Meeting",
                "verbose_name_plural": "Board Meetings",
                "ordering": ["-meeting_date"],
            },
        ),
        migrations.CreateModel(
            name="FinancialReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                            ("event_based", "Event-Based"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Report Type",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Period Start")),
                ("period_end", models.DateField(verbose_name="Period End")),
                (
                    "total_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Income",
                    ),
                ),
                (
                    "total_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Expenses",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Balance",
                    ),
                ),
                ("report_content", models.TextField(verbose_name="Report Content")),
                (
                    "verified_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Verified Date"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        help_text="Treasurer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Generated By",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Statutory Auditor",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Report",
                "verbose_name_plural": "Financial Reports",
                "ordering": ["-period_end", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancialTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        max_length=10,
                        verbose_name="Transaction Type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("membership_fees", "Membership Fees"),
                            ("event_proceeds", "Event Proceeds"),
                            ("donations", "Donations"),
                            ("bequests", "Bequests"),
                            ("financial_aid", "Financial Aid"),
                            ("operational", "Operational Expenses"),
                            ("event_expenses", "Event Expenses"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Category",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False,
                        help_text="Expenses require 3 signatures: President, Treasurer, Statutory Auditor",
                        verbose_name="Requires Approval",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Transaction",
                "verbose_name_plural": "Financial Transactions",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssemblyVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote_type",
                    models.CharField(
                        choices=[
                            ("resolution", "Resolution"),
                            ("election", "Election"),
                            ("amendment", "Amendment"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Vote Type",
                    ),
                ),
                (
                    "voting_method",
                    models.CharField(
                        choices=[
                            ("show_of_hands", "Show of Hands"),
                            ("secret_ballot", "Secret Ballot"),
                        ],
                        default="show_of_hands",
                        max_length=20,
                        verbose_name="Voting Method",
                    ),
                ),
                ("question", models.TextField(verbose_name="Question/Proposal")),
                (
                    "votes_yes",
                    models.PositiveIntegerField(default=0, verbose_name="Votes Yes"),
                ),
                (
                    "votes_no",
                    models.PositiveIntegerField(default=0, verbose_name="Votes No"),
                ),
                (
                    "votes_abstain",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Votes Abstain"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        help_text='e.g., "Approved", "Rejected"',
                        max_length=20,
                        null=True,
                        verbose_name="Result",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Published within 30 days as per Article 24",
                        verbose_name="Published",
                    ),
                ),
                (
                    "published_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Published Date"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agenda_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="votes",
                        to="governance.agendaitem",
                        verbose_name="Agenda Item",
                    ),
                ),
                (
                    "assembly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="governance.generalassembly",
                        verbose_name="General Assembly",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assembly Vote",
                "verbose_name_plural": "Assembly Votes",
                "ordering": ["assembly", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member_type",
                    models.CharField(
                        choices=[
                            ("student", "Student Member"),
                            ("active", "Active Member"),
                            ("sympathizer", "Sympathizer"),
                        ],
                        default="student",
                        max_length=20,
                        verbose_name="Member Type",
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Registration Date"
                    ),
                ),
                (
                    "membership_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Membership Start Date"
                    ),
                ),
                (
                    "membership_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Membership End Date"
                    ),
                ),
                (
                    "lazio_residence_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Verified that member lives in Lazio region",
                        verbose_name="Lazio Residence Verified",
                    ),
                ),
                (
                    "cameroonian_origin_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Verified that member is Cameroonian or of Cameroonian origin",
                        verbose_name="Cameroonian Origin Verified",
                    ),
                ),
                (
                    "is_active_member",
                    models.BooleanField(
                        default=False,
                        help_text="Regularly participates in General Assemblies and pays contributions",
                        verbose_name="Active Member",
                    ),
                ),
                (
                    "last_assembly_attendance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Assembly Attendance"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about this member",
                        null=True,
                        verbose_name="Notes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
                "ordering": ["-registration_date"],
            },
        ),
        migrations.AddField(
            model_name="disciplinarycase",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disciplinary_cases",
                to="governance.member",
                verbose_name="Member",
            ),
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contribution_type",
                    models.CharField(
                        choices=[
                            ("annual_dues", "Annual Dues"),
                            ("event_contribution", "Event Contribution"),
                            ("donation", "Donation"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Contribution Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date"
                    ),
                ),
                (
                    "purpose",
                    models.TextField(blank=True, null=True, verbose_name="Purpose"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="governance.member",
                        verbose_name="Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contribution",
                "verbose_name_plural": "Contributions",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MembershipStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("expelled", "Expelled"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Effective Date"
                    ),
                ),
                (
                    "last_payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Payment Date"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for status change",
                        null=True,
                        verbose_name="Reason",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="governance.member",
                        verbose_name="Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership Status",
                "verbose_name_plural": "Membership Statuses",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="AuditorMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_president",
                    models.BooleanField(
                        default=False,
                        help_text="President of the Board of Auditors",
                        verbose_name="President",
                    ),
                ),
                (
                    "is_founding_member",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically included as founding member",
                        verbose_name="Founding Member",
                    ),
                ),
                (
                    "is_former_president",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically included as former president",
                        verbose_name="Former President",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auditor_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="governance.boardofauditors",
                        verbose_name="Board of Auditors",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditor Member",
                "verbose_name_plural": "Auditor Members",
                "ordering": ["board", "-is_president", "user"],
                "unique_together": {("board", "user")},
            },
        ),
        migrations.CreateModel(
            name="ElectionVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("president", "President"),
                            ("vice_president", "Vice-President"),
                            ("secretary_general", "Secretary General"),
                            ("deputy_secretary_general", "Deputy Secretary General"),
                            ("treasurer", "Treasurer"),
                            ("statutory_auditor", "Statutory Auditor"),
                            (
                                "communication_culture_manager",
                                "Communication and Culture Manager",
                            ),
                        ],
                        max_length=50,
                        verbose_name="Position",
                    ),
                ),
                (
                    "vote_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Vote Timestamp"
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes_received",
                        to="governance.candidacy",
                        verbose_name="Candidate",
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="governance.election",
                        verbose_name="Election",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="election_votes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Voter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Election Vote",
                "verbose_name_plural": "Election Votes",
                "ordering": ["election", "position", "vote_timestamp"],
                "unique_together": {("election", "voter", "position")},
            },
        ),
        migrations.CreateModel(
            name="CommissionMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("president", "President"),
                            ("vice_president", "Vice-President"),
                            ("secretary", "Secretary"),
                            ("communication_officer", "Communication Officer"),
                            ("advisor", "Advisor"),
                            ("scrutineer", "Scrutineer"),
                        ],
                        max_length=30,
                        verbose_name="Role",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "commission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="governance.electoralcommission",
                        verbose_name="Electoral Commission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commission Member",
                "verbose_name_plural": "Commission Members",
                "ordering": ["commission", "role"],
                "unique_together": {("commission", "user")},
            },
        ),
        migrations.CreateModel(
            name="ExecutivePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("president", "President"),
                            ("vice_president", "Vice-President"),
                            ("secretary_general", "Secretary General"),
                            ("deputy_secretary_general", "Deputy Secretary General"),
                            ("treasurer", "Treasurer"),
                            ("statutory_auditor", "Statutory Auditor"),
                            (
                                "communication_culture_manager",
                                "Communication and Culture Manager",
                            ),
                        ],
                        max_length=50,
                        verbose_name="Position",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resigned", "Resigned"),
                            ("replaced", "Replaced"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "resignation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Resignation Date"
                    ),
                ),
                (
                    "resignation_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Resignation Reason"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="governance.executiveboard",
                        verbose_name="Executive Board",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executive_positions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Executive Position",
                "verbose_name_plural": "Executive Positions",
                "ordering": ["board", "position"],
                "unique_together": {("board", "position")},
            },
        ),
        migrations.CreateModel(
            name="ExpenseApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signature_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Signature Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("signed", "Signed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "signer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Signer",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="governance.financialtransaction",
                        verbose_name="Transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Approval",
                "verbose_name_plural": "Expense Approvals",
                "ordering": ["transaction", "created_at"],
                "unique_together": {("transaction", "signer")},
            },
        ),
        migrations.CreateModel(
            name="AssemblyAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendee_name",
                    models.CharField(
                        blank=True,
                        help_text="Name if not a registered user",
                        max_length=200,
                        null=True,
                        verbose_name="Attendee Name",
                    ),
                ),
                (
                    "attendee_type",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("active_member", "Active Member"),
                            ("sympathizer", "Sympathizer"),
                            ("guest", "Guest"),
                            ("authority", "Authority/Institution"),
                        ],
                        max_length=20,
                        verbose_name="Attendee Type",
                    ),
                ),
                (
                    "attended",
                    models.BooleanField(default=True, verbose_name="Attended"),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registered At"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assembly_attendances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "assembly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="governance.generalassembly",
                        verbose_name="General Assembly",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assembly Attendance",
                "verbose_name_plural": "Assembly Attendances",
                "ordering": ["assembly", "attendee_type", "user"],
                "unique_together": {("assembly", "user")},
            },
        ),
        migrations.CreateModel(
            name="MembershipDues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2020),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Year",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="€10 for members, €5 for sympathizers",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        help_text="March 31 of the year", verbose_name="Due Date"
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Payment Date"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("online", "Online Payment"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("waived", "Waived"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dues",
                        to="governance.member",
                        verbose_name="Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership Dues",
                "verbose_name_plural": "Membership Dues",
                "ordering": ["-year", "member"],
                "unique_together": {("member", "year")},
            },
        ),
    ]
