# Generated by Django 5.2.8 on 2025-12-02 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssemblyVoteRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No"), ("abstain", "Abstain")],
                        max_length=10,
                        verbose_name="Choice",
                    ),
                ),
                (
                    "vote_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Vote Timestamp"
                    ),
                ),
                (
                    "vote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_records",
                        to="governance.assemblyvote",
                        verbose_name="Assembly Vote",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assembly_vote_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Voter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assembly Vote Record",
                "verbose_name_plural": "Assembly Vote Records",
                "ordering": ["vote", "vote_timestamp"],
                "unique_together": {("vote", "voter")},
            },
        ),
    ]
