# Generated by Django 5.2.8 on 2025-12-02 21:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governance", "0002_assemblyvoterecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_founding_member",
            field=models.BooleanField(
                default=False,
                help_text="Founding member of ASCAI Association (automatically included in Board of Auditors per Article 8)",
                verbose_name="Founding Member",
            ),
        ),
        migrations.AlterField(
            model_name="assemblyvote",
            name="voting_method",
            field=models.CharField(
                choices=[
                    ("show_of_hands", "Show of Hands"),
                    ("secret_ballot", "Secret Ballot"),
                ],
                default="show_of_hands",
                help_text="Article 36: Show of hands for resolutions, secret ballot for elections",
                max_length=20,
                verbose_name="Voting Method",
            ),
        ),
        migrations.AlterField(
            model_name="election",
            name="election_type",
            field=models.CharField(
                choices=[("executive_board", "Executive Board")],
                default="executive_board",
                help_text="Currently only Executive Board elections",
                max_length=50,
                verbose_name="Election Type",
            ),
        ),
        migrations.CreateModel(
            name="RulesOfProcedureAmendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Amendment Title"),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the proposed amendment",
                        verbose_name="Amendment Description",
                    ),
                ),
                (
                    "proposed_article",
                    models.CharField(
                        blank=True,
                        help_text="Article number being amended (if applicable)",
                        max_length=100,
                        null=True,
                        verbose_name="Article Number",
                    ),
                ),
                (
                    "proposal_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Proposal Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("approved", "Approved for Assembly"),
                            ("rejected", "Rejected"),
                            ("discussed", "Discussed"),
                            ("adopted", "Adopted"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="proposed",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "meets_deadline",
                    models.BooleanField(
                        default=False,
                        help_text="Proposed at least 30 days before assembly",
                        verbose_name="Meets 30-Day Deadline",
                    ),
                ),
                (
                    "discussion_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Discussion Notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposed_amendments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Proposed By",
                    ),
                ),
                (
                    "target_assembly",
                    models.ForeignKey(
                        help_text="Assembly where this amendment will be discussed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendment_proposals",
                        to="governance.generalassembly",
                        verbose_name="Target Assembly",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rules of Procedure Amendment",
                "verbose_name_plural": "Rules of Procedure Amendments",
                "ordering": ["-proposal_date", "-created_at"],
            },
        ),
    ]
