# Generated by Django 5.2.8 on 2026-01-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governance", "0003_member_is_founding_member_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipdues",
            name="valid_from",
            field=models.DateField(
                blank=True,
                help_text="Membership validity start date (automatically set to January 1st when 10 EUR is paid)",
                null=True,
                verbose_name="Valid From",
            ),
        ),
        migrations.AddField(
            model_name="membershipdues",
            name="valid_until",
            field=models.DateField(
                blank=True,
                help_text="Membership validity end date (automatically set to December 31st when 10 EUR is paid)",
                null=True,
                verbose_name="Valid Until",
            ),
        ),
    ]
