# Generated by Django 5.2.8 on 2026-04-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governance", "0004_membershipdues_valid_from_membershipdues_valid_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executiveposition",
            name="position",
            field=models.CharField(
                help_text="Enter an existing executive role or define a new one for this board.",
                max_length=100,
                verbose_name="Position",
            ),
        ),
    ]
