# Generated by Django 4.2.26 on 2025-11-24 21:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("universities", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="arrival_year",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2100),
                ],
                verbose_name="Arrival Year in Italy",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="city_in_lazio",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rome", "Rome"),
                    ("latina", "Latina"),
                    ("frosinone", "Frosinone"),
                    ("rieti", "Rieti"),
                    ("viterbo", "Viterbo"),
                ],
                max_length=50,
                null=True,
                verbose_name="City in Lazio",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="Email Verified"),
        ),
        migrations.AddField(
            model_name="user",
            name="field_of_study",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Field of Study / Profession",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True,
                help_text="Your full name",
                max_length=200,
                null=True,
                verbose_name="Full Name",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_preferences",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="User notification settings",
                verbose_name="Notification Preferences",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="occupation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "Student"),
                    ("worker", "Worker"),
                    ("job_seeker", "Job Seeker"),
                    ("researcher", "Researcher"),
                ],
                max_length=20,
                null=True,
                verbose_name="Occupation",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profession",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Profession"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="universities.university",
                verbose_name="University",
            ),
        ),
        migrations.CreateModel(
            name="UserDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("id_card", "ID Card"),
                            ("student_card", "Student Card"),
                            ("residence_permit", "Residence Permit"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="user_documents/%Y/%m/", verbose_name="File"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this document has been verified by an admin.",
                        verbose_name="Verified",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Admin notes about this document.",
                        null=True,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Document",
                "verbose_name_plural": "User Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
