# Generated by Django 5.2.14 on 2026-05-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_language_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language_preference",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "Français"), ("it", "Italiano")],
                default="en",
                max_length=2,
                verbose_name="Language Preference",
            ),
        ),
    ]
