#!/usr/bin/env python
"""
Helper script to create a .env file for local development.
This script will guide you through setting up your local environment.
"""
import os
from pathlib import Path

def create_env_file():
    """Create a .env file with user input."""
    env_path = Path('.env')
    
    if env_path.exists():
        response = input('.env file already exists. Overwrite? (y/N): ')
        if response.lower() != 'y':
            print('Cancelled. Existing .env file preserved.')
            return
    
    print('\n' + '='*60)
    print('Local Environment Setup')
    print('='*60)
    print('\nThis will create a .env file for local development.\n')
    
    # Django settings
    print('1. Django Settings:')
    secret_key = input('   SECRET_KEY (press Enter for default): ').strip()
    if not secret_key:
        secret_key = 'django-insecure-change-me-in-production'
    
    # Database settings
    print('\n2. Database Settings (press Enter for defaults):')
    db_name = input('   DB_NAME [ASCAI-V2]: ').strip() or 'ASCAI-V2'
    db_user = input('   DB_USER [postgres]: ').strip() or 'postgres'
    db_password = input('   DB_PASSWORD []: ').strip()
    db_host = input('   DB_HOST [localhost]: ').strip() or 'localhost'
    db_port = input('   DB_PORT [5432]: ').strip() or '5432'
    
    # Email settings
    print('\n3. Email Configuration:')
    print('   Choose email backend:')
    print('   1. Console (emails print to terminal - default)')
    print('   2. Gmail SMTP (sends real emails)')
    email_choice = input('   Choice [1]: ').strip() or '1'
    
    email_backend = 'django.core.mail.backends.console.EmailBackend'
    email_host = 'smtp.gmail.com'
    email_port = '587'
    email_use_tls = 'True'
    email_user = ''
    email_password = ''
    default_from = 'ASCAI Lazio <noreply@ascailazio.org>'
    
    if email_choice == '2':
        email_backend = 'django.core.mail.backends.smtp.EmailBackend'
        email_user = input('   EMAIL_HOST_USER (your Gmail): ').strip()
        email_password = input('   EMAIL_HOST_PASSWORD (App Password): ').strip()
        if email_user:
            default_from = f'ASCAI Lazio <{email_user}>'
        print('\n   Note: For Gmail, you need an App Password.')
        print('   Get it from: https://myaccount.google.com/apppasswords')
        print('   IMPORTANT: Remove ALL spaces from the App Password!')
    
    # Build .env content
    env_content = f"""# Local Development Environment Configuration
# Generated by setup_local_env.py

# Django Settings
DJANGO_SETTINGS_MODULE=config.settings.development
DEBUG=True
SECRET_KEY={secret_key}

# Hosts
ALLOWED_HOSTS=localhost,127.0.0.1
CSRF_TRUSTED_ORIGINS=http://localhost:8000,http://127.0.0.1:8000

# Database Configuration
DB_ENGINE=django.db.backends.postgresql
DB_NAME={db_name}
DB_USER={db_user}
DB_PASSWORD={db_password}
DB_HOST={db_host}
DB_PORT={db_port}

# Email Configuration
EMAIL_BACKEND={email_backend}
EMAIL_HOST={email_host}
EMAIL_PORT={email_port}
EMAIL_USE_TLS={email_use_tls}
EMAIL_HOST_USER={email_user}
EMAIL_HOST_PASSWORD={email_password}
DEFAULT_FROM_EMAIL={default_from}
CONTACT_EMAIL=info@ascailazio.org

# Localization
DEFAULT_LANGUAGE=en

# Site Domain
SITE_DOMAIN=localhost:8000
"""
    
    # Write .env file
    try:
        with open(env_path, 'w', encoding='utf-8') as f:
            f.write(env_content)
        print('\n' + '='*60)
        print('SUCCESS: .env file created!')
        print('='*60)
        print(f'\nFile created at: {env_path.absolute()}')
        
        if email_choice == '2' and email_user:
            print('\nNext steps:')
            print('1. Test email: python manage.py test_email your-email@gmail.com')
            print('2. If authentication fails, check GMAIL_SETUP_GUIDE.md')
        else:
            print('\nNext steps:')
            print('1. Test email: python manage.py test_email test@example.com')
            print('2. Email will print to console (not actually sent)')
            print('3. To send real emails, edit .env and set EMAIL_BACKEND to SMTP')
        
        print('\n')
    except Exception as e:
        print(f'\nERROR: Failed to create .env file: {e}')
        return False
    
    return True

if __name__ == '__main__':
    create_env_file()



















