# Generated by Django 5.1.1 on 2025-11-24 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="University Name"),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("rome", "Rome"),
                            ("cassino", "Cassino"),
                            ("viterbo", "Viterbo"),
                            ("latina", "Latina"),
                            ("frosinone", "Frosinone"),
                            ("rieti", "Rieti"),
                        ],
                        max_length=50,
                        verbose_name="City",
                    ),
                ),
                ("address", models.TextField(verbose_name="Address")),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Phone"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "tuition_range_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Minimum Tuition (EUR)",
                    ),
                ),
                (
                    "tuition_range_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Maximum Tuition (EUR)",
                    ),
                ),
                (
                    "languages",
                    models.JSONField(
                        default=list,
                        help_text='List of languages offered (e.g., ["Italian", "English"])',
                        verbose_name="Languages of Instruction",
                    ),
                ),
                (
                    "degree_types",
                    models.JSONField(
                        default=list,
                        help_text='List of degree types (e.g., ["Bachelor", "Master", "PhD"])',
                        verbose_name="Degree Types",
                    ),
                ),
                (
                    "fields_of_study",
                    models.JSONField(
                        default=list,
                        help_text='List of fields (e.g., ["Engineering", "Medicine", "Law"])',
                        verbose_name="Fields of Study",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="universities/logos/",
                        verbose_name="Logo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "University",
                "verbose_name_plural": "Universities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UniversityProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Program Name")),
                (
                    "degree_type",
                    models.CharField(
                        choices=[
                            ("bachelor", "Bachelor"),
                            ("master", "Master"),
                            ("phd", "PhD"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Degree Type",
                    ),
                ),
                (
                    "field",
                    models.CharField(max_length=100, verbose_name="Field of Study"),
                ),
                (
                    "duration_years",
                    models.PositiveIntegerField(verbose_name="Duration (Years)"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("italian", "Italian"),
                            ("english", "English"),
                            ("french", "French"),
                            ("bilingual", "Bilingual"),
                        ],
                        max_length=20,
                        verbose_name="Language of Instruction",
                    ),
                ),
                (
                    "tuition",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Tuition (EUR)",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "requirements",
                    models.TextField(
                        blank=True, null=True, verbose_name="Requirements"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="universities.university",
                        verbose_name="University",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program",
                "verbose_name_plural": "Programs",
                "ordering": ["university", "name"],
            },
        ),
        migrations.CreateModel(
            name="SavedUniversity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saved_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Saved At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_universities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by_users",
                        to="universities.university",
                        verbose_name="University",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved University",
                "verbose_name_plural": "Saved Universities",
                "ordering": ["-saved_at"],
                "unique_together": {("user", "university")},
            },
        ),
    ]
