# Generated by Django 5.2.8 on 2026-01-22 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("downloads", "0003_document_download_limit_document_expiry_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text='Icon class name (e.g., "folder", "document", "link")',
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Resource Category",
                "verbose_name_plural": "Resource Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="StudentGuideSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome to ASCAI Lazio"),
                            ("before_arrival", "Before Arrival"),
                            ("arrival", "Arrival & First Steps"),
                            ("enrollment", "University Enrollment"),
                            ("living", "Living in Lazio"),
                            ("membership", "ASCAI Membership"),
                            ("resources", "Resources & Support"),
                        ],
                        max_length=50,
                        verbose_name="Section Type",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Main content for this section.",
                        verbose_name="Content",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text='Icon class name (e.g., "home", "school", "info")',
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Guide Section",
                "verbose_name_plural": "Guide Sections",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ResourceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured resources appear prominently on the resources page.",
                        verbose_name="Featured",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_links",
                        to="students.resourcecategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Link",
                "verbose_name_plural": "Resource Links",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="StudentGuideStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="guide_images/%Y/%m/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional video URL (YouTube, Vimeo, etc.)",
                        null=True,
                        verbose_name="Video URL",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "related_resources",
                    models.ManyToManyField(
                        blank=True,
                        related_name="guide_steps",
                        to="downloads.document",
                        verbose_name="Related Resources",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="students.studentguidesection",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guide Step",
                "verbose_name_plural": "Guide Steps",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="StudentGuideProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Completed"),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(auto_now=True, verbose_name="Last Accessed"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guide_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="students.studentguidesection",
                        verbose_name="Section",
                    ),
                ),
                (
                    "completed_steps",
                    models.ManyToManyField(
                        blank=True,
                        related_name="completed_by_users",
                        to="students.studentguidestep",
                        verbose_name="Completed Steps",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guide Progress",
                "verbose_name_plural": "Guide Progress",
                "ordering": ["-last_accessed"],
                "unique_together": {("user", "section")},
            },
        ),
    ]
