# Generated by Django 5.2.14 on 2026-05-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_conversionevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="associationsettings",
            name="map_embed_url",
            field=models.URLField(
                blank=True,
                help_text="Paste a Google Maps embed URL for the public contact page.",
                verbose_name="Map Embed URL",
            ),
        ),
        migrations.AddField(
            model_name="associationsettings",
            name="map_link_url",
            field=models.URLField(
                blank=True,
                help_text="Optional public map link opened in a new tab.",
                verbose_name="Map Link URL",
            ),
        ),
        migrations.AddField(
            model_name="associationsettings",
            name="public_location",
            field=models.CharField(
                blank=True,
                default="Rome and the Lazio region, Italy",
                max_length=255,
                verbose_name="Public Location",
            ),
        ),
    ]
