# Generated by Django 5.1.1 on 2025-11-24 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("file", models.FileField(upload_to="documents/", verbose_name="File")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("reddito", "Reddìto Forms"),
                            ("enrollment", "Enrollment Documents"),
                            ("visa", "Visa-Related Documents"),
                            ("guidelines", "ASCAI Lazio Guidelines"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Download Count"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        help_text="Automatically detected from file extension.",
                        max_length=10,
                        verbose_name="File Type",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
