# Generated by Django 4.2.26 on 2025-11-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("downloads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_reserved",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this document is only accessible to authenticated users in the reserved area.",
                verbose_name="Reserved Area Only",
            ),
        ),
    ]
