# Generated by Django 5.2.8 on 2026-01-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("downloads", "0002_document_is_reserved"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="download_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of downloads allowed (leave blank for unlimited)",
                null=True,
                verbose_name="Download Limit",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="expiry_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date after which document is no longer available",
                null=True,
                verbose_name="Expiry Date",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="file_size",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Automatically calculated from file",
                null=True,
                verbose_name="File Size (bytes)",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="preview_url",
            field=models.URLField(
                blank=True,
                help_text="URL for document preview (e.g., Google Docs viewer)",
                null=True,
                verbose_name="Preview URL",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text='Comma-separated tags (e.g., "form, visa, application")',
                max_length=500,
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Thumbnail image for document preview",
                null=True,
                upload_to="documents/thumbnails/",
                verbose_name="Thumbnail",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
