# Generated by Django 4.2.26 on 2025-11-24 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diaspora", "0002_lifeinitaly_successstoryimage_testimonial_and_more"),
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "video_type",
                    models.CharField(
                        choices=[("youtube", "YouTube"), ("vimeo", "Vimeo")],
                        default="youtube",
                        max_length=10,
                        verbose_name="Video Type",
                    ),
                ),
                (
                    "video_id",
                    models.CharField(
                        help_text="For YouTube: enter the video ID (e.g., dQw4w9WgXcQ). For Vimeo: enter the video ID from the URL.",
                        max_length=100,
                        verbose_name="Video ID",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="gallery/videos/",
                        verbose_name="Thumbnail",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_videos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="diaspora.event",
                        verbose_name="Related Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Video",
                "verbose_name_plural": "Gallery Videos",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
