# Generated by Django 5.2.14 on 2026-05-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_galleryvideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryvideo",
            name="external_thumbnail_url",
            field=models.URLField(
                blank=True,
                help_text="Optional thumbnail URL for Vimeo or externally hosted video images.",
                verbose_name="External Thumbnail URL",
            ),
        ),
    ]
