# Generated by Django 5.1.1 on 2025-11-24 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(verbose_name="Description")),
                ("location", models.CharField(max_length=200, verbose_name="Location")),
                (
                    "start_datetime",
                    models.DateTimeField(verbose_name="Start Date & Time"),
                ),
                ("end_datetime", models.DateTimeField(verbose_name="End Date & Time")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/",
                        verbose_name="Event Image",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Is Published"),
                ),
                (
                    "registration_required",
                    models.BooleanField(
                        default=False, verbose_name="Registration Required"
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Max Participants"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "Français")],
                        default="en",
                        max_length=2,
                        verbose_name="Language",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organized_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Organizer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("academic", "Academic"),
                            ("cultural", "Cultural"),
                            ("integration", "Integration"),
                            ("success_story", "Success Story"),
                            ("announcement", "Announcement"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/",
                        verbose_name="Featured Image",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Published At"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Only published news will be visible to users.",
                        verbose_name="Is Published",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "Français")],
                        default="en",
                        max_length=2,
                        verbose_name="Language",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news_articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
