# Generated by Django 4.2.26 on 2025-11-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diaspora", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LifeInItaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bureaucracy", "Bureaucracy"),
                            ("health", "Healthcare"),
                            ("documents", "Documents & Permits"),
                            ("housing", "Housing"),
                            ("work", "Work & Employment"),
                            ("education", "Education"),
                            ("transportation", "Transportation"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="life_in_italy/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured articles appear on the main diaspora page.",
                        verbose_name="Featured",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Is Published"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "Français")],
                        default="en",
                        max_length=2,
                        verbose_name="Language",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Life in Italy",
                "verbose_name_plural": "Life in Italy Articles",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SuccessStoryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="success_stories/additional/", verbose_name="Image"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Caption"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Success Story Image",
                "verbose_name_plural": "Success Story Images",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text='e.g., "Student at Sapienza University" or "Software Engineer"',
                        max_length=200,
                        verbose_name="Title/Position",
                    ),
                ),
                ("testimonial", models.TextField(verbose_name="Testimonial")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        default="Lazio, Italy", max_length=200, verbose_name="Location"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured testimonials appear on the main diaspora page.",
                        verbose_name="Featured",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Is Published"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "Français")],
                        default="en",
                        max_length=2,
                        verbose_name="Language",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SuccessStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "person_name",
                    models.CharField(max_length=200, verbose_name="Person Name"),
                ),
                (
                    "person_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Person Title/Position"
                    ),
                ),
                ("story", models.TextField(verbose_name="Success Story")),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="success_stories/",
                        verbose_name="Featured Image",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured stories appear on the main diaspora page.",
                        verbose_name="Featured",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Is Published"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "Français")],
                        default="en",
                        max_length=2,
                        verbose_name="Language",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "additional_images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="success_stories",
                        to="diaspora.successstoryimage",
                        verbose_name="Additional Images",
                    ),
                ),
            ],
            options={
                "verbose_name": "Success Story",
                "verbose_name_plural": "Success Stories",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
