# Generated by Django 5.2.8 on 2026-01-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diaspora", "0002_lifeinitaly_successstoryimage_testimonial_and_more"),
        ("downloads", "0003_document_download_limit_document_expiry_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="capacity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total capacity for the event (same as max_participants if not specified)",
                null=True,
                verbose_name="Capacity",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("cultural", "Cultural"),
                    ("educational", "Educational"),
                    ("social", "Social"),
                    ("networking", "Networking"),
                    ("sports", "Sports"),
                    ("workshop", "Workshop"),
                    ("seminar", "Seminar"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
                verbose_name="Event Type",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="location_map",
            field=models.URLField(
                blank=True,
                help_text="Google Maps or other map service URL",
                null=True,
                verbose_name="Location Map URL",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for event registration",
                null=True,
                verbose_name="Registration Deadline",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="related_resources",
            field=models.ManyToManyField(
                blank=True,
                help_text="Documents related to this event",
                related_name="events",
                to="downloads.document",
                verbose_name="Related Resources",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="event",
            name="waitlist_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Allow users to join waitlist when event is full",
                verbose_name="Enable Waitlist",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "Français"), ("it", "Italiano")],
                default="en",
                max_length=2,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="lifeinitaly",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "Français"), ("it", "Italiano")],
                default="en",
                max_length=2,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "Français"), ("it", "Italiano")],
                default="en",
                max_length=2,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="successstory",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "Français"), ("it", "Italiano")],
                default="en",
                max_length=2,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "Français"), ("it", "Italiano")],
                default="en",
                max_length=2,
                verbose_name="Language",
            ),
        ),
    ]
