# Generated by Django 5.2.8 on 2026-01-22 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentorship", "0002_mentorrating"),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorSpecialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class name",
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Mentor Specialization",
                "verbose_name_plural": "Mentor Specializations",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="availability_calendar",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='JSON structure for availability schedule (e.g., {"monday": ["09:00-12:00"], "tuesday": ["14:00-17:00"]})',
                verbose_name="Availability Calendar",
            ),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="mentors/profiles/",
                verbose_name="Profile Image",
            ),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="response_time",
            field=models.CharField(
                blank=True,
                help_text='e.g., "Within 24 hours", "Within 2-3 days"',
                max_length=50,
                verbose_name="Average Response Time",
            ),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="success_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Percentage of successful mentorship sessions",
                max_digits=5,
                verbose_name="Success Rate (%)",
            ),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="MentorshipSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="Scheduled At")),
                (
                    "duration",
                    models.DurationField(
                        help_text="Session duration (e.g., 1:00:00 for 1 hour)",
                        verbose_name="Duration",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location or video call link",
                        max_length=200,
                        verbose_name="Location",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Session notes or agenda",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Completed"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="Rating given after session completion",
                        null=True,
                        verbose_name="Session Rating",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="mentorship.mentorshiprequest",
                        verbose_name="Request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mentorship Session",
                "verbose_name_plural": "Mentorship Sessions",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="specializations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select one or more specializations.",
                related_name="mentors",
                to="mentorship.mentorspecialization",
                verbose_name="Specializations",
            ),
        ),
    ]
