# Generated by Django 5.1.1 on 2025-11-24 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("provider", models.CharField(max_length=200, verbose_name="Provider")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("EUR", "EUR (€)"), ("USD", "USD ($)")],
                        default="EUR",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "eligibility_criteria",
                    models.TextField(verbose_name="Eligibility Criteria"),
                ),
                (
                    "application_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="Application Deadline"
                    ),
                ),
                (
                    "application_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Application URL"
                    ),
                ),
                (
                    "is_disco_lazio",
                    models.BooleanField(
                        default=False,
                        help_text="Mark this if this is a DISCO Lazio scholarship",
                        verbose_name="DISCO Lazio Scholarship",
                    ),
                ),
                (
                    "requirements_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="scholarships/requirements/",
                        verbose_name="Requirements Document",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("deadline_passed", "Deadline Passed"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Scholarship",
                "verbose_name_plural": "Scholarships",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedScholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saved_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Saved At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_scholarships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "scholarship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by_users",
                        to="scholarships.scholarship",
                        verbose_name="Scholarship",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Scholarship",
                "verbose_name_plural": "Saved Scholarships",
                "ordering": ["-saved_at"],
                "unique_together": {("user", "scholarship")},
            },
        ),
    ]
