# Generated by Django 4.2.26 on 2025-11-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scholarships", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarship",
            name="level",
            field=models.CharField(
                choices=[
                    ("bachelor", "Bachelor's Degree"),
                    ("master", "Master's Degree"),
                    ("phd", "PhD"),
                    ("all", "All Levels"),
                ],
                default="all",
                help_text="Education level this scholarship is for",
                max_length=20,
                verbose_name="Level",
            ),
        ),
        migrations.AddField(
            model_name="scholarship",
            name="region",
            field=models.CharField(
                choices=[
                    ("lazio", "Lazio"),
                    ("all", "All Regions"),
                    ("other", "Other"),
                ],
                default="all",
                help_text="Region this scholarship applies to",
                max_length=20,
                verbose_name="Region",
            ),
        ),
    ]
